services:
  - type: web
    name: beefood-backend
    env: node
    branch: main
    root: backend
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    disk: 1024
    envVars:
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: "production"
