PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Tenant (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  isOpen BOOLEAN NOT NULL DEFAULT 1,
  image TEXT
);

CREATE TABLE IF NOT EXISTS User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'STUDENT',
  balance REAL NOT NULL DEFAULT 100000,
  phoneNumber TEXT,
  nim TEXT,
  avatar TEXT,
  tenantId INTEGER UNIQUE,
  FOREIGN KEY (tenantId) REFERENCES Tenant(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Menu (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  price REAL NOT NULL,
  estimatedTime INTEGER NOT NULL,
  isAvailable BOOLEAN NOT NULL DEFAULT 1,
  image TEXT,
  tenantId INTEGER NOT NULL,
  FOREIGN KEY (tenantId) REFERENCES Tenant(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Order" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  tenantId INTEGER NOT NULL,
  totalPrice REAL NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  items TEXT NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (tenantId) REFERENCES Tenant(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Feedback (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  orderId INTEGER NOT NULL UNIQUE,
  rating INTEGER NOT NULL,
  comment TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (orderId) REFERENCES "Order"(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS WalletTransaction (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  type TEXT NOT NULL,
  method TEXT NOT NULL,
  amount REAL NOT NULL,
  description TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
